import = [
  "./themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "none"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS NF"

size = 12
